branches:
  only:
  - master

cache:
  directories:
  - node_modules

addons:
  apt:
    packages:
    - wine4.7

matrix:
  include:
    #########################################
    # Static web deployment to github pages #
    #########################################
    - name: static_web
      language: node_js
      node_js:
      - "stable"
      script:
      - npm test
      - npm run build

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
          branch: master

    ############################################
    # Electron build and deploy to gh releases #
    ############################################
    - name: electron
      services:
      - docker
      language: node_js
      node_js:
      - "stable"
      os: linux
      script:
      - yarn
      - yarn electron-pack

      before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "gmoehler"
      - git config --local user.email "gregor.moehler@gmx.de"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

      deploy:
        provider: releases
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        file_glob: true
        file: dist/LuminosiaStudio*
        on:
          tags: true
