branches:
  only:
    - master

language: node_js
node_js:
  - "stable"

matrix:
  include:
    #########################################
    # Static web deployment to github pages #
    #########################################
    - name: static_web
      cache:
        directories:
          - node_modules
      script:
        - npm test
        - npm run build

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
          branch: master

    ############################################
    # Electron build and deploy to gh releases #
    ############################################
    - name: electron
      services:
      - docker
      cache:
        directories:
          - node_modules
          - $HOME/.cache/electron
          - $HOME/.cache/electron-builder

      before_install:
        # replace version with next release
        - npx semantic-release --dryRun 2>&1 | tee dryrun.out
        - nextver=`grep "The next release version is" dryrun.out | sed 's/.*next release version is \([0-9.]\+\)*.*/\1/'`
        - echo $nextver
        - if [ -n "$nextver" ]; then sed -i -e "s/0.0.0-semantic-release/$nextver/g" package.json; fi
        - head package.json
        # make scripts executable
        - chmod a+x ./resources/linux/*/*
        # setup env for docker build
        - env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_' | grep -v '/home/travis' > .env
        - cat .env
        # pull docker image
        - docker pull electronuserland/builder:wine

      script:
        - |
          docker run --rm \
            --env-file .env \
            --env ELECTRON_CACHE="/root/.cache/electron" \
            --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
            -v ${PWD}:/project \
            -v ${PWD##*/}-node-modules:/project/node_modules \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine bash -c "yarn && yarn electron-pack"
        - ls -l dist

      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

      deploy:
        provider: script
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        script: 
          - npx semantic-release
