branches:
  only:
  - master

cache:
  directories:
  - node_modules

matrix:
  include:
    #########################################
    # Static web deployment to github pages #
    #########################################
    - language: node_js
      node_js:
      - "stable"
      script:
      - npm test
      - npm run build

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
          branch: master

    #########################################
    # Static web deployment to github pages #
    #########################################
    - language: node_js
      node_js:
      - "stable"
      os: windows
      script:
      - npm electron-pack

      deploy:
        provider: releases
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          tags: true
