branches:
  only:
  - master

cache:
  directories:
  - node_modules

matrix:
  include:
    #########################################
    # Static web deployment to github pages #
    #########################################
    - name: static_web
      language: node_js
      node_js:
      - "stable"
      script:
      - npm test
      - npm run build

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
          branch: master

    ############################################
    # Electron build and deploy to gh releases #
    ############################################
    - name: electron
      services:
      - docker
      language: node_js
      node_js:
      - "stable"

      script:
      - env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_' > .env
      - cat .env
      - |
        docker run --rm -ti \
          --env-file .env \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          -v ${PWD}:/project \
          -v ${PWD##*/}-node-modules:/project/node_modules \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine && yarn && yarn electron-pack
      - ls 
      - ls dist

      before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "gmoehler"
      - git config --local user.email "gregor.moehler@gmx.de"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

      before_cache:
      - rm -rf $HOME/.cache/electron-builder/wine

      deploy:
        provider: releases
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        file_glob: true
        file: dist/LuminosiaStudio*
        on:
          tags: true
