// action type constants

// channel actions
export const LOAD_CHANNEL_STARTED = "LOAD_CHANNEL_STARTED";
export const LOAD_CHANNEL_SUCCESS = "LOAD_CHANNEL_SUCCESS";
export const LOAD_CHANNEL_FAILURE = "LOAD_CHANNEL_FAILURE";
export const LOAD_MULTICHANNEL_STARTED = "LOAD_MULTICHANNEL_STARTED";
export const LOAD_MULTICHANNEL_SUCCESS = "LOAD_MULTICHANNEL_SUCCESS";
export const LOAD_MULTICHANNEL_FAILURE = "LOAD_MULTICHANNEL_FAILURE";
export const PLAY_CHANNELS = "PLAY_CHANNELS";
export const STOP_CHANNELS = "STOP_CHANNELS";
export const MOVE_CHANNEL = "MOVE_CHANNEL";
export const ADD_PART = "ADD_PART";
export const DELETE_PART = "DELETE_PART"; 

// image list actions
export const ADD_IMAGE = "ADD_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const LOAD_IMAGELIST_STARTED = "LOAD_IMAGELIST_STARTED";
export const LOAD_IMAGELIST_SUCCESS = "LOAD_IMAGELIST_SUCCESS";
export const LOAD_IMAGELIST_FAILURE = "LOAD_IMAGELIST_FAILURE";

// view actions
export const SELECT = "SELECT";
export const SET_RESOLUTION = "SET_RESOLUTION";
export const SET_CHANNEL_PLAY_STATE = "SET_CHANNEL_PLAY_STATE";
export const SET_MODE = "SET_MODE";
export const SET_MARKER = "SET_MARKER";
export const DELETE_MARKER = "DELETE_MARKER";
export const UPDATE_MARKER = "UPDATE_MARKER";
export const SET_SELECTED = "SET_SELECTED";
export const DESELECT = "DESELECT";
